### ISSUE TITLE
Error when emitting a BOOL param as part of contract event

### ISSUE THREAD

**Issue by stephen101** [ConsenSys/eventeum#127]
I have eventeum running in docker using the eventeum/eventeum:latest image. I can receive contract events without a problem. However when I try to subscribe to an event that has a BOOL parameter I get an `Unsupported type: bool` error.

This is the entry in `contractEventFilter` :
 
         {"_id":"LoanStarted","contractAddress":"0x59712F44CDbAD771E8761035C6d3B4A5611c6D7F","node":"default","eventSpecification":{"eventName":"LoanStarted","indexedParameterDefinitions":[],"nonIndexedParameterDefinitions":[{"position":{"$numberInt":"0"},"type":"UINT256"},{"position":{"$numberInt":"1"},"type":"ADDRESS"},{"position":{"$numberInt":"2"},"type":"ADDRESS"},{"position":{"$numberInt":"3"},"type":"UINT256"},{"position":{"$numberInt":"4"},"type":"UINT256"},{"position":{"$numberInt":"5"},"type":"UINT256"},{"position":{"$numberInt":"6"},"type":"UINT256"},{"position":{"$numberInt":"7"},"type":"UINT256"},{"position":{"$numberInt":"8"},"type":"UINT256"},{"position":{"$numberInt":"9"},"type":"ADDRESS"},{"position":{"$numberInt":"10"},"type":"ADDRESS"},{"position":{"$numberInt":"11"},"type":"BOOL"}]},"startBlock":"6267926","_class":"net.consensys.eventeum.dto.event.filter.ContractEventFilter"}`

The event in Solidity looks like this :

    event LoanStarted(
        uint256 loanId,
        address borrower,
        address lender,
        uint256 loanPrincipalAmount,
        uint256 maximumRepaymentAmount,
        uint256 nftCollateralId,
        uint256 loanStartTime,
        uint256 loanDuration,
        uint256 loanInterestRateForDurationInBasisPoints,
        address nftCollateralContract,
        address loanERC20Denomination,
        bool interestIsProRated
    );

When the event fires I get the following logs in the Eventeum service:

    DEBUG net.consensys.eventeum.chain.service.Web3jService: lambda$registerEventListener$0 -      
    Dispatching log: Log{removed=false, logIndex='0x6', transactionIndex='0x7', transactionHash='0x3934b2643608849ba2b1c83251ad69ee6ea12eb6ac700ad8b9778b5d10c2c9ea', blockHash='0x5174501c37803e7baa66984fc34ab1b98410f7c3b2a1bf586c25c35318f621f5', blockNumber='0x5fa470', address='0x59712f44cdbad771e8761035c6d3b4a5611c6d7f', data='0x0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000f2730c7d84aa9fe0c7bad3fd7ca1e763e3c3f3df000000000000000000000000685d05cafada2e26d8d2df2ea06dc113817735610000000000000000000000000000000000000000000000000de0b6b3a764000000000000000000000000000000000000000000000000000010a741a462780000000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000005e8b1dc3000000000000000000000000000000000000000000000000000000000000000700000000000000000000000000000000000000000000000000000000ffffffff000000000000000000000000fdf703b22a13f825d348af43d2bfc140054d0e3d000000000000000000000000c778417e063141139fce010982780140aa0cd5ab0000000000000000000000000000000000000000000000000000000000000000', type='null', topics=[0x7a9a95acdaec2726663658ce76ffb4b960ce244a001b3252a5bb3db586e28c1b]}

    2020-04-06 12:17:11.096 [pool-3-thread-5] ERROR org.web3j.protocol.core.filters.Filter: lambda$run$25 - Error sending request

    rx.exceptions.OnErrorNotImplementedException: Unsupported type: bool

    at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386) ~[rxjava-1.3.8.jar!/:1.3.8]

    at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383) ~[rxjava-1.3.8.jar!/:1.3.8]

    at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44) ~[rxjava-1.3.8.jar!/:1.3.8]

    at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153) ~[rxjava-1.3.8.jar!/:1.3.8]

    at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115) ~[rxjava-1.3.8.jar!/:1.3.8]

    at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:212) ~[rxjava-1.3.8.jar!/:1.3.8]

    at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139) ~[rxjava-1.3.8.jar!/:1.3.8]

    at org.web3j.protocol.core.filters.LogFilter.process(LogFilter.java:39) ~[core-3.6.0.jar!/:na]

    at org.web3j.protocol.core.filters.Filter.pollFilter(Filter.java:129) ~[core-3.6.0.jar!/:na]

    at org.web3j.protocol.core.filters.Filter.lambda$run$25(Filter.java:83) ~[core-3.6.0.jar!/:na]

    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_222]

    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_222]

    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_222]

    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_222]

    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_222]

    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_222]

    at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_222]

    Caused by: net.consensys.eventeum.chain.converter.TypeConversionException: Unsupported type: bool

    at net.consensys.eventeum.chain.converter.Web3jEventParameterConverter.convert(Web3jEventParameterConverter.java:53) ~[eventeum-core-0.7.0-RELEASE.jar!/:0.7.0-RELEASE]

    at net.consensys.eventeum.chain.converter.Web3jEventParameterConverter.convert(Web3jEventParameterConverter.java:21) ~[eventeum-core-0.7.0-RELEASE.jar!/:0.7.0-RELEASE]

    at net.consensys.eventeum.chain.factory.DefaultContractEventDetailsFactory.lambda$typeListToParameterList$0(DefaultContractEventDetailsFactory.java:78) ~[eventeum-core-0.7.0-RELEASE.jar!/:0.7.0-RELEASE]

    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_222]

    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[na:1.8.0_222]

    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[na:1.8.0_222]

    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[na:1.8.0_222]

    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_222]

    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_222]

    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[na:1.8.0_222]

    at net.consensys.eventeum.chain.factory.DefaultContractEventDetailsFactory.typeListToParameterList(DefaultContractEventDetailsFactory.java:79) ~[eventeum-core-0.7.0-RELEASE.jar!/:0.7.0-RELEASE]

    at net.consensys.eventeum.chain.factory.DefaultContractEventDetailsFactory.createEventDetails(DefaultContractEventDetailsFactory.java:42) ~[eventeum-core-0.7.0-RELEASE.jar!/:0.7.0-RELEASE]

    at net.consensys.eventeum.chain.service.Web3jService.lambda$registerEventListener$0(Web3jService.java:109) ~[eventeum-core-0.7.0-RELEASE.jar!/:0.7.0-RELEASE]

    at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39) ~[rxjava-1.3.8.jar!/:1.3.8]

    at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134) ~[rxjava-1.3.8.jar!/:1.3.8]

    ... 10 common frames omitted

    2020-04-06 12:17:11.096 [pool-3-thread-1] ERROR org.web3j.protocol.core.filters.Filter: lambda$run$25 - Error sending request

**Comment by craigwilliams84** [comment]
Hey Stephen!  From your stack trace, it looks like you're running version 0.7.0 of Eventeum.  This should be fixed in the latest 0.8.0 release.  Try upgrading and let me know if you're still having issues.

**Comment by craigwilliams84** [comment]
Hey, did updating to the latest version fix this issue?

**Comment by craigwilliams84** [comment]
Integration tests cover boolean events so I think this was a versioning issue.   Feel free to reopen if you're still having problems!

**Comment by stephen101** [comment]
Hi there,

Sorry for the late reply. Upgrading to 0.8 worked. I was using the
eventeum/eventeum:latest docker image. I thought that was v 0.8 but turns
out it’s still 0.7 swapping to a different image worked. Thanks
