### ISSUE TITLE
BlockEvents Kafka Topic not created

### ISSUE THREAD

**Issue by tzumby** [ConsenSys/eventeum#16]
Hi there,

First off, thanks for this awesome project. I've been looking around and it seems like the only open source project out there built for serious event processing.

I'm running this locally with docker-compose and connecting Infura via websockets. Here are some details about my environment:

```
 java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```

I used the following ENV variables for eventeum in docker-compose:

```
    environment:
      ETHEREUM_BLOCKSTRATEGY: PUBSUB
      ETHEREUM_NODE_URL: wss://mainnet.infura.io/ws
```

I'm running with docker-compose up and I also attached to the kafka container and tried to list the topics

```
confluent@bfc1895ae4c6:/$ kafka-topics --list --zookeeper zookeeper:2181
__consumer_offsets
filter-events-dlteventeum
```

Based on the docs it seems that the block-events topic should be created automatically. Am I missing something ? 

Thanks a lot!

**Comment by tzumby** [comment]
Interesting enough, if I create an event filter I can see the block-events topic getting in there:

```
{
	"id": "ck",
	"contractAddress": "0x06012c8cf97BEaD5deAe237070F9587f8E7A266d",
	"eventSpecification": {
		"eventName": "Transfer",
		"indexedParameterDefinitions": [],
		"nonIndexedParameterDefinitions": [
		  {"position": 0, "type": "ADDRESS"},
		  {"position": 1, "type": "ADDRESS"},
		  {"position": 2, "type": "UINT256"}
		 ] 
	},
	"correlationIdStrategy": {
		"type": "NON_INDEXED_PARAMETER",
		"parameterIndex": 0 
	}
}
```

But now I get a null pointer exception:

```
eventeum_1   | Exception in thread "pool-4-thread-18" java.lang.NullPointerException
eventeum_1   |  at net.consensys.eventeum.chain.service.strategy.PollingBlockSubscriptionStrategy.blockToBlockDetails(PollingBlockSubscriptionStrategy.java:29)
eventeum_1   |  at net.consensys.eventeum.chain.service.strategy.PollingBlockSubscriptionStrategy.lambda$null$0(PollingBlockSubscriptionStrategy.java:19)
eventeum_1   |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
eventeum_1   |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
eventeum_1   |  at java.lang.Thread.run(Thread.java:748)
```

**Comment by craigwilliams84** [comment]
Hi, that is strange.  The block-events topic should be created on first startup of Eventeum.  I'll look into this.

The second issue you are seeing is something that I have also come across.  The Infura support is very new and there is an issue with web3j not providing block hash information through websockets.  Therefore in Eventeum we retrieve the block details via web3j.ethGetBlockByNumber after being notified of a new block.  The problem with this is that because infura has many nodes behind a load balancer, in some cases this new block has not yet been broadcast to all nodes, and this NPE occurs when a node is hit that does not yet know about the new block.

My PR to fix the block hash omission in web3j has been merged, and I'm waiting on a new release, as SNAPSHOT releases are not published.  In the meantime, eventeum should still work for contract event broadcasting (although the logs will be full of NullPointerException's), assuming that new block messages are not critical within your application.

**Comment by tzumby** [comment]
Hey @craigwilliams84,

Thanks for responding so fast :). You're right, as soon as I used my own Parity node those errors were gone.
