### ISSUE TITLE
Cannot consume messages when using kafka secured connection

### ISSUE THREAD

**Issue by selimyanat** [ConsenSys/eventeum#88]
When kafka is configured through a secure connection (see pull request for the fix: https://github.com/ConsenSys/eventeum/pull/87) , the consumer does not get all the configuration because it does not use the configured kafka listener connection factory (see `KafkaConfiguration.eventeumConsumerFactory` and `KafkaConfiguration.defaultConsumerFactory`).  You can find the exception stack down below:

I have investigated the issue, it seems that the kafka dead letter component is not able to get the configured kafka factory (see `EventeumServerConfiguration`). 

```
2019-10-07 10:08:14.321 [main] DEBUG org.apache.kafka.common.network.Selector: pollSelectionKeys - [Consumer clientId=consumer-1, groupId=dlt] Connection with <MY_KAFKA_BROKERS> disconnected
java.io.EOFException: null
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:119) ~[kafka-clients-2.0.0.jar:na]
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:335) ~[kafka-clients-2.0.0.jar:na]
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:296) ~[kafka-clients-2.0.0.jar:na]
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:560) [kafka-clients-2.0.0.jar:na]
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:496) [kafka-clients-2.0.0.jar:na]
	at org.apache.kafka.common.network.Selector.poll(Selector.java:425) [kafka-clients-2.0.0.jar:na]
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:510) [kafka-clients-2.0.0.jar:na]
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:271) [kafka-clients-2.0.0.jar:na]
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:242) [kafka-clients-2.0.0.jar:na]
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:218) [kafka-clients-2.0.0.jar:na]
	at org.apache.kafka.clients.consumer.internals.Fetcher.getTopicMetadata(Fetcher.java:274) [kafka-clients-2.0.0.jar:na]
	at org.apache.kafka.clients.consumer.KafkaConsumer.partitionsFor(KafkaConsumer.java:1774) [kafka-clients-2.0.0.jar:na]
	at org.apache.kafka.clients.consumer.KafkaConsumer.partitionsFor(KafkaConsumer.java:1742) [kafka-clients-2.0.0.jar:na]
	at org.springframework.kafka.listener.AbstractMessageListenerContainer.checkTopics(AbstractMessageListenerContainer.java:275) [spring-kafka-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.kafka.listener.ConcurrentMessageListenerContainer.doStart(ConcurrentMessageListenerContainer.java:135) [spring-kafka-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.kafka.listener.AbstractMessageListenerContainer.start(AbstractMessageListenerContainer.java:257) [spring-kafka-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.kafka.config.KafkaListenerEndpointRegistry.startIfNecessary(KafkaListenerEndpointRegistry.java:289) [spring-kafka-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.kafka.config.KafkaListenerEndpointRegistry.start(KafkaListenerEndpointRegistry.java:238) [spring-kafka-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182) [spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53) [spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360) [spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158) [spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122) [spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:879) [spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:161) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) [spring-context-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at net.consensys.eventeumserver.Application.main(Application.java:15) [classes/:na]	

2019-10-07 10:10:01.924 [main] DEBUG org.apache.kafka.clients.NetworkClient: handleDisconnections - [Consumer clientId=consumer-1, groupId=dlt] Node -1 disconnected.
2019-10-07 10:10:01.924 [main] DEBUG org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient: fireCompletion - [Consumer clientId=consumer-1, groupId=dlt] Cancelled request with header RequestHeader(apiKey=METADATA, apiVersion=6, clientId=consumer-1, correlationId=8) due to node -1 being disconnected
2019-10-07 10:10:02.026 [main] DEBUG org.apache.kafka.clients.NetworkClient: maybeUpdate - [Consumer clientId=consumer-1, groupId=dlt] Give up sending metadata request since no node is available
2019-10-07 10:10:02.128 [main] DEBUG org.apache.kafka.clients.NetworkClient: maybeUpdate - [Consumer clientId=consumer-1, groupId=dlt] Give up sending metadata request since no node is available
2019-10-07 10:10:02.229 [main] DEBUG org.apache.kafka.clients.NetworkClient: maybeUpdate - [Consumer clientId=consumer-1, groupId=dlt] Give up sending metadata request since no node is available
2019-10-07 10:10:02.333 [main] DEBUG org.apache.kafka.clients.NetworkClient: maybeUpdate - [Consumer clientId=consumer-1, groupId=dlt] Give up sending metadata request since no node is available
2019-10-07 10:10:02.438 [main] DEBUG org.apache.kafka.clients.NetworkClient: maybeUpdate - [Consumer clientId=consumer-1, groupId=dlt] Give up sending metadata request since no node is available
2019-10-07 10:10:02.538 [main] DEBUG org.apache.kafka.clients.NetworkClient: maybeUpdate - [Consumer clientId=consumer-1, groupId=dlt] Give up sending metadata request since no node is available
2019-10-07 10:10:02.639 [main] DEBUG org.apache.kafka.clients.NetworkClient: maybeUpdate - [Consumer clientId=consumer-1, groupId=dlt] Give up sending metadata request since no node is available
2019-10-07 10:10:02.741 [main] DEBUG org.apache.kafka.clients.NetworkClient: maybeUpdate - [Consumer clientId=consumer-1, groupId=dlt] Give up sending metadata request since no node is available	


```

**Comment by Ferparishuertas** [comment]
@selimyanat Still having this issue?

thanks
